version: '3.9'

networks:
  symfony_net:

services:

  api:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: '${API_NAME}-server'
    ports:
      - '${API_PORT}:80'
    working_dir: /var/www/html
    volumes:
      - ./_api:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini

  app:
    build:
      context: ./_frontend
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-server'
    ports:
      - ${APP_PORT}:80
